### ISSUE TITLE
Enabling New Relic Servers for Docker

### ISSUE THREAD

**Issue by janantala** [tutumcloud/newrelic-agent#3]
Is it possible to enable server for docker containers?
https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/enabling-new-relic-servers-docker

**Comment by fermayo** [comment]
It is enabled. You should see all your containers in the Virtualization tab on New Relic.

**Comment by janantala** [comment]
Oh, my bad. I have forgotten `"/var/run/docker.sock:/var/run/docker.sock"` volume.

**Comment by fermayo** [comment]
No problem!
